name: Prune GHCR

on:
  pull_request:
    types: [closed]

  workflow_dispatch:

env:
  IMAGE_NAME: mill1000/msmart-ng

jobs:
  prune-pr-images:
    # if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          container: ${{ env.IMAGE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
          prune-tags-regexes: ^pr-${{github.event.pull_request.number}}
