name: Prune GHCR

on:
  pull_request:
    types: [closed]

env:
  IMAGE_NAME: mill1000/msmart-ng

jobs:
  prune-images:
    # if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          container: ${{ IMAGE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
          prune-tag-regexes: ^pr-${{github.event.pull_request.number}}
